### ISSUE TITLE
运行过一段时间后，出现了panic

### ISSUE THREAD

**Issue by zerak** [cfanbo/delayqueue#2]
![image](https://github.com/cfanbo/delayqueue/assets/2040699/ce0ea144-79f9-4e13-906d-ed027b069a95)

**Comment by cfanbo** [comment]
您好，由于以前调整过代码，未进行发布， 目前已发布了v0.0.15版本，您升级一下版本为最新版本，看一下是否还存在此问题。

**Comment by cfanbo** [comment]
您好，由于以前调整过代码但未立即发布， 目前已发布了v0.0.15版本，您升级一下版本为最新版本，看一下是否还存在此问题。
